### ISSUE TITLE
questions on the feature predictions

### ISSUE THREAD

**Issue by zijin-gu** [ozcelikfu/IC-GAN_fMRI_Reconstruction#4]
Hi,

I am really impressed by the results from your paper. While looking at your code, I had a question.

I noticed that you did this step to the feature prediction:

```
std_norm_test_latent = (pred_test_latent - np.mean(pred_test_latent,axis=0)) / np.std(pred_test_latent,axis=0)
pred_instance = std_norm_test_latent * np.std(train_instance,axis=0) + np.mean(train_instance,axis=0)
```
Can you please explain why this is necessary? I try to train the same ridge regression model but without adding the training mean/std back the reconstruction looks bad.

Thanks!

**Comment by ozcelikfu** [comment]
This was a method I got from another paper (Milad et al BigBiGAN), I think it is always better to transform distribution of your predictions to training set distribution
