### ISSUE TITLE
How to get the file in the path ‘saved_regression_models/’

### ISSUE THREAD

**Issue by Aurora-1412** [ozcelikfu/IC-GAN_fMRI_Reconstruction#5]
Thank you for your detailed environment construction and code operation steps. However, in train_regression.py, there is a file path named saved_regression_models which I don't find in the repository:
`with open(f"saved_regression_models/Subject{sub}_regressionanalysis_instancevector2048dim.p","wb") as f:`

I'd be extremely grateful if you could tell me where I can get it or how to generate it myself.

**Comment by Aurora-1412** [comment]
I'm sorry for bothering. I make a simple mistake. Just create the directory and all is ok.

**Comment by dlmdlmacy** [comment]
Hello, lyh!

I guess you've successfully run the project, and do you know how where to find Subject*.mat file? I only found .h5 file in KamitaniLab's project.

Thank you very very very much if you can reply!

**Comment by Aurora-1412** [comment]
Hello!
&nbsp; I have just gone to bed, if it is not urgent, I'd like to tell you the web link tommorow morning.
&nbsp; The link is in the article,&nbsp; it may be "https:\\brainliner.jp"
&nbsp; By the way, I am not completely successful. The instance feature I generate from extract_feature.py is not good. But if you use the feature provided by the author, everything goes well. I checked the code but cannot tell what is wrong.&nbsp; If you also meet the problem, please tell me. Maybe we can help each other.

---Original---
From: ***@***.***&gt;
Date: Fri, Mar 10, 2023 00:14 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [ozcelikfu/IC-GAN_fMRI_Reconstruction] How to get the file in the path ‘saved_regression_models/’ (Issue #5)




 
Hello, lyh!
 
I guess you've successfully run the project, and do you know how where to find Subject*.mat file? I only found .h5 file in KamitaniLab's project.
 
Thank you very very very much if you can reply!

**Comment by Aurora-1412** [comment]
The link is&nbsp;http://brainliner.jp/data/brainliner/Generic_Object_Decoding&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ozcelikfu/IC-GAN_fMRI_Reconstruction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 凌晨0:14
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ozcelikfu/IC-GAN_fMRI_Reconstruction] How to get the file in the path ‘saved_regression_models/’ (Issue #5)





 
Hello, lyh!
 
I guess you've successfully run the project, and do you know how where to find Subject*.mat file? I only found .h5 file in KamitaniLab's project.
 
Thank you very very very much if you can reply!

**Comment by dlmdlmacy** [comment]
> The link is&nbsp;http://brainliner.jp/data/brainliner/Generic_Object_Decoding&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ozcelikfu/IC-GAN_fMRI_Reconstruction" ***@***.***&gt;; 发送时间:&nbsp;2023年3月10日(星期五) 凌晨0:14 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [ozcelikfu/IC-GAN_fMRI_Reconstruction] How to get the file in the path ‘saved_regression_models/’ (Issue #5) Hello, lyh! I guess you've successfully run the project, and do you know how where to find Subject*.mat file? I only found .h5 file in KamitaniLab's project. Thank you very very very much if you can reply! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

Thank you for your help! And I've reconstructed the images successfully.

Because I just want to reconstruct images, I haven't run the extract_feature.py. Maybe it's not stable and need some tricks like the auther said in [this issue](https://github.com/ozcelikfu/IC-GAN_fMRI_Reconstruction/issues/3#issuecomment-1222290828)?

Hope your study goes well! And if I got any other idea, I'll tell you so we can discuss it.

**Comment by happylufei** [comment]
> 你好啊，我遇到了和你一样的问题，你目前有思路吗？理论上实例特征并不需要训练，不清楚为什么会不一样，用.py生成的图像偏黑。我在运行extract_feature.py报了一些错，接下来我打算研究一下，如果你有了新的发现，我们一起交流一下吧

**Comment by Aurora-1412** [comment]
> > 你好啊，我遇到了和你一样的问题，你目前有思路吗？理论上实例特征并不需要训练，不清楚为什么会不一样，用.py生成的图像偏黑。我在运行extract_feature.py报了一些错，接下来我打算研究一下，如果你有了新的发现，我们一起交流一下吧

我没有报错，请问是什么错误呢。运行代码的时候我只遇到了cuda版本不匹配RTX 3090，和某个torch.tensor报warning，要改成torch.as_tensor 这两个问题

**Comment by happylufei** [comment]
> 

using resnet50 to extract features
Loading pretrained weights from:  ./ic_gan/swav_pretrained.pth.tar
key  projection_head.0.weight  not in dict
key  projection_head.0.bias  not in dict
key  projection_head.1.weight  not in dict
key  projection_head.1.bias  not in dict
key  projection_head.1.running_mean  not in dict
key  projection_head.1.running_var  not in dict
key  projection_head.1.num_batches_tracked  not in dict
key  projection_head.3.weight  not in dict
key  projection_head.3.bias  not in dict
key  prototypes.weight  not in dict
Network key  fc.weight  not in dict to load
Network key  fc.bias  not in dict to load
除了这个，我也觉得只要代码一样，那就不应该出现其他问题，是不是加载的预训练模型不对？

**Comment by Aurora-1412** [comment]
> > 
> 
> using resnet50 to extract features Loading pretrained weights from: ./ic_gan/swav_pretrained.pth.tar key projection_head.0.weight not in dict key projection_head.0.bias not in dict key projection_head.1.weight not in dict key projection_head.1.bias not in dict key projection_head.1.running_mean not in dict key projection_head.1.running_var not in dict key projection_head.1.num_batches_tracked not in dict key projection_head.3.weight not in dict key projection_head.3.bias not in dict key prototypes.weight not in dict Network key fc.weight not in dict to load Network key fc.bias not in dict to load 除了这个，我也觉得只要代码一样，那就不应该出现其他问题，是不是加载的预训练模型不对？

我觉得不是的，首先代码里确实有把预训练模型中没有的key print出来，然后我找到了SwAV的原论文，从原论文的github仓库里下载下来的resnet50预训练模型和本仓库提供的link里的预训练模型是一致的。

**Comment by DavisMeee** [comment]
> 

Hey,seems that you've successfully run the project, but how did you solve this problem?
