### ISSUE TITLE
How to get './KamitaniData/fmri_data/Subject*.mat'?

### ISSUE THREAD

**Issue by dlmdlmacy** [ozcelikfu/IC-GAN_fMRI_Reconstruction#6]
Hello,
Thank you for your excellent job!

I only found *.h5 files in [Generic Object Decoding](https://github.com/KamitaniLab/GenericObjectDecoding), so I am wondering how to get ./KamitaniData/fmri_data/Subject*.mat? Is there any special preprocess to convert .h5 file to .mat file?

Thank you a lot! And wish you have a nice day!

**Comment by ozcelikfu** [comment]
Thank you for your kind comments on the paper! You can access the mat files from this link: http://brainliner.jp/data/brainliner/Generic_Object_Decoding 

I hope this helps with your work.
My pleasure, have a nice day!

**Comment by dlmdlmacy** [comment]
Thank you so much, it solves the problem perfectly!

**Comment by Aurora-1412** [comment]
> Thank you for your kind comments on the paper! You can access the mat files from this link: http://brainliner.jp/data/brainliner/Generic_Object_Decoding
> 
> I hope this helps with your work. My pleasure, have a nice day!

Hello,  thank you for your wonderful work.

The instance feature I generate from extract_feature.py is not good. (In specific, the reconstructed image is nearly black) But everything goes well if I use the extracted feature provided in the hub. I checked the code but cannot tell what is wrong. What should I do to get a better instance feature, or does it need some tricks?

I'd be extremely grateful if you could guide me. Thank you very much.

**Comment by ozcelikfu** [comment]
I am not sure about the exact problem but there shouldn't be any problem with extracting instance features. You may check pre and post processing of the images maybe? Or how different is the instance features that you extracted and the ones we provide?

**Comment by Aurora-1412** [comment]
The generative extracted features include much more zeros than the provided, which, I think, cause the reconstructed image almost completely black.  I change the cuda version to adjust to my GPU, which also seems not crucial to the reconstruction.
