### ISSUE TITLE
Question about the Guidance on Modifying Feature Extractor in IC-GAN Code for Graduate Thesis Completion

### ISSUE THREAD

**Issue by DungBui007** [ozcelikfu/IC-GAN_fMRI_Reconstruction#8]
Hi,
I really thank you for your research. Currently, I am doing my graduate thesis on this topic and am re-running the code you wrote. I wonder if you can tell me if this code can be changed in the feature_extractor_name section or somewhere else (I really need this to be able to complete my thesis)? For example, is there a different feature_extractor_name instead of "selfsupervised"?

Thank you very much!
`feature_extractor_name = 'selfsupervised'`

**Comment by ozcelikfu** [comment]
Hi,

It should work as it is if the original IC-GAN repo is working without an
issue. Good luck with your thesis!

Best,
Furkan

Touyaaa ***@***.***>, 2 Tem 2024 Sal, 14:18 tarihinde şunu
yazdı:

**Comment by DungBui007** [comment]
I want to make changes such as modifying a function or parameter to create a comparison table. Could you please give me some advice?

**Comment by ozcelikfu** [comment]
You may try using various pretrained IC-GAN models on different resolution,
dataset or backbone as it is listed in the icgan repository (shown below)
[image: image.png]

I think that can be a good comparison. I hope this helps.

Best,
Furkan

Touyaaa ***@***.***>, 2 Tem 2024 Sal, 14:49 tarihinde şunu
yazdı:

**Comment by DungBui007** [comment]
Thanks for your help

Best regards,
Touyaa
